### ISSUE TITLE
Failed to import linked account Fanatical games details

### ISSUE THREAD

**Issue by SparrowBrain** [nosyn00b/playnite-fanatical-plugin#3]
After buying some games recently the extension started throwing an exception during import.
```
12-04 10:33:40.179|INFO |FanaticalLibrary#FanaticalAccountClient:Current Playnite.SDK, Version=6.9.0.0, Culture=neutral, PublicKeyToken=null does not support Javascript Event Messaging. Using old way unoptimized strategy
12-04 10:33:40.779|INFO |FanaticalLibrary#FanaticalAccountClient:Current authentication token is valid.
12-04 10:33:41.647|ERROR|FanaticalLibrary#FanaticalLibrary:Failed to import linked account Fanatical games details.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '[0].order.gift_order', line 1, position 973.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 336
   at Playnite.Common.DataSerializer.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 80
   at Playnite.SDK.Data.Serialization.FromJson[T](String json) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:line 406
   at FanaticalLibrary.Services.FanaticalAccountClient.GetLibraryItems() in D:\Develop\GitProjects\playnite-fanatical-plugin\source\Services\FanaticalAccountClient.cs:line 475
   at FanaticalLibrary.FanaticalLibrary.GetLibraryItems() in D:\Develop\GitProjects\playnite-fanatical-plugin\source\FanaticalLibrary.cs:line 44
   at FanaticalLibrary.FanaticalLibrary.GetGames(LibraryGetGamesArgs args) in D:\Develop\GitProjects\playnite-fanatical-plugin\source\FanaticalLibrary.cs:line 61
```

Will try to get the actual JSON if I can at a later time.

**Comment by Rondrian82** [comment]
I have the exact same problem., with the same Exception in the Log File.

**Comment by nosyn00b** [comment]
Hi, 
   It seems some of the games you purchased have some unexpected value in the "gift_order" attribute that broke the JSON syntax expected from the Newtonsoft JSON library.  

To have a better check we need the JSON as you suggest (and possibly some detail about the game that perhaps broke the syntax). 

You can get the JSON a bit more easily using GOG Galaxy with the Playnite library connector: there are more debugging options in that, and if I remember correctly you can also extract the JSON (hoping it's extracted "before the parsing" if it's a parsing problem).

**Comment by Rondrian82** [comment]
Do you know how I can get the JSON in Playnite. If I know, where I can get it, I could provide it... Which game(s) make the problem, I don't know... I have quite a lot Keys in my Fanatical account.

**Comment by nosyn00b** [comment]
Sadly I confirm that the GOG plugin's first login was broken by some of the last Fanatical site releases... let me check and possibly solve that problem first: I do not remember any simple OOTB way to have the JSON in the Playnite plugin. Hopefully, I'll come back to this thread when solved the other one!

**Comment by nosyn00b** [comment]
Ok, it seems I have to play a bit with the deserializer, will use this JSON (that seems to be perfectly valid) as an example...

**Comment by nosyn00b** [comment]
Released a new, hopefully fixed, version, let me know if it's ok!

**Comment by Rondrian82** [comment]
> Released a new, hopefully fixed, version, let me know if it's ok!

It's working now! No Errors and Keys are imported. Thank you :-)

**Comment by Rondrian82** [comment]
One thing: Is it possible to automatically delete the Fanatical entries in Playnite after I redeemed the keys? I only want to have Fanatical game entries in my library, if I don't have the key redeemed. At the moment, after the key was imported, it remains in my library - if I don't want that, I have to delete it manually.
It would be great, if that would be possible (maybe optinal).

**Comment by SparrowBrain** [comment]
No more errors on my side either. Great job!

**Comment by nosyn00b** [comment]
@Rondrian82, the Plugung Library lacks support for this. I asked Josef Nemes himself, owner of the Pynite project, if can be added, getting a formal no-go ... see https://github.com/JosefNemec/Playnite/issues/2677.

You can try adding a comment to that thread if you want to support the request. 

I will close this thread asap, being the issue solved.
